application: resellerapisample
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: .*
  script: main.app

